name: Spark Native Engine Benchmark (Gluten Change)

on:
  workflow_dispatch:
    inputs:
      benchmark:
        default: 'tpcds'
        description: 'Benchmark to run (tpcds or tpch)'
        required: true
        type: string
      benchmark-scale:
        default: '10'
        description: 'Scale factor for benchmark, like: tiny, 1, 10, 100, 1000...'
        required: true
        type: string
      gluten-repository-first:
        default: 'apache/incubator-gluten'
        description: 'The repository of first gluten to build'
        required: false
        type: string
      gluten-ref-first:
        default: 'main'
        description: 'The commit id of first gluten to build'
        required: false
        type: string
      gluten-repository-second:
        default: 'apache/incubator-gluten'
        description: 'The repository of first gluten to build'
        required: false
        type: string
      gluten-ref-second:
        description: 'The commit id of second gluten to build'
        required: true
        type: string

permissions:
  issues: write

jobs:
  build-native-engine:
    name: Build Native Engine (Gluten Change)
    strategy:
      fail-fast: false
      matrix:
        java-version: [ '8' ]
        spark-version: [ '3.5.4' ]
    uses: ./.github/workflows/build-native-engine.yml
    with:
      java-version: ${{ matrix.java-version }}
      spark-version: ${{ matrix.spark-version }}
    secrets: inherit
  build-benchmark:
    name: Build Benchmark (Gluten Change)
    strategy:
      fail-fast: false
      matrix:
        java-version: [ '8' ]
        spark-version: [ '3.5.4' ]
    uses: ./.github/workflows/build-benchmark.yml
    with:
      java-version: ${{ matrix.java-version }}
      spark-version: ${{ matrix.spark-version }}
      benchmark: ${{ inputs.benchmark }}
      benchmark-scale: ${{ inputs.benchmark-scale }}
    secrets: inherit
  run-benchmark:
    name: Run Benchmark (Gluten Change)
    needs: [build-native-engine, build-benchmark]
    strategy:
      fail-fast: false
      matrix:
        java-version: [ '8' ]
        spark-version: [ '3.5.4' ]
    uses: ./.github/workflows/run-gluten-change-benchmark.yml
    with:
      java-version: ${{ matrix.java-version }}
      spark-version: ${{ matrix.spark-version }}
      benchmark: ${{ inputs.benchmark }}
      benchmark-scale: ${{ inputs.benchmark-scale }}
      gluten-repository-first: ${{ inputs.gluten-repository-first }}
      gluten-ref-first: ${{ inputs.gluten-ref-first }}
      gluten-repository-second: ${{ inputs.gluten-repository-second }}
      gluten-ref-second: ${{ inputs.gluten-ref-second }}
    secrets: inherit