name: Build Native Engines

on:
  workflow_call:
    inputs:
      os:
        default: 'ubuntu-latest'
        required: false
        type: string
      java-version:
        default: '8'
        required: false
        type: string
      spark-version:
        default: '3.5.4'
        required: false
        type: string
      spark-binary-version:
        default: '3.5'
        required: false
        type: string
      scala-version:
        default: '2.12.17'
        required: false
        type: string
      scala-binary-version:
        default: '2.12'
        required: false
        type: string
      comet-repository:
        default: 'apache/datafusion-comet'
        required: false
        type: string
      comet-ref:
        default: 'main'
        required: false
        type: string
      auron-repository:
        default: 'apache/auron'
        required: false
        type: string
      auron-ref:
        default: 'master'
        required: false
        type: string
      gluten-repository:
        default: 'apache/gluten'
        required: false
        type: string
      gluten-ref:
        default: 'main'
        required: false
        type: string
    outputs:
      comet-cache-key:
        description: 'Cache key of the built comet jar'
        value: ${{ jobs.build-comet.outputs.cache-key }}
      auron-cache-key:
        description: 'Cache key of the built auron jar'
        value: ${{ jobs.build-auron.outputs.cache-key }}
      gluten-cache-key:
        description: 'Cache key of the built gluten jar'
        value: ${{ jobs.build-gluten.outputs.cache-key }}

permissions:
  issues: write

jobs:
  build-comet:
    name: Build comet
    runs-on: ${{ inputs.os }}
    outputs:
      cache-key: ${{ steps.build.outputs.cache-key }}
    steps:
      - uses: actions/checkout@v5
      - name: Build Datafusion Comet
        id: build
        uses: ./.github/actions/build-comet
        with:
          java-version: ${{ inputs.java-version }}
          spark-binary-version: ${{ inputs.spark-binary-version }}
          scala-binary-version: ${{ inputs.scala-binary-version }}
          repository: ${{ inputs.comet-repository }}
          ref: ${{ inputs.comet-ref }}

  build-auron:
    name: Build auron
    runs-on: ${{ inputs.os }}
    outputs:
      cache-key: ${{ steps.build.outputs.cache-key }}
    steps:
      - uses: actions/checkout@v5
      - name: Build Auron
        id: build
        uses: ./.github/actions/build-auron
        with:
          java-version: ${{ inputs.java-version }}
          spark-binary-version: ${{ inputs.spark-binary-version }}
          scala-binary-version: ${{ inputs.scala-binary-version }}
          repository: ${{ inputs.auron-repository }}
          ref: ${{ inputs.auron-ref }}

  build-gluten:
    name: Build gluten
    runs-on: ${{ inputs.os }}
    outputs:
      cache-key: ${{ steps.build.outputs.cache-key }}
    steps:
      - uses: actions/checkout@v5
      - name: Build Gluten
        id: build
        uses: ./.github/actions/build-gluten
        with:
          java-version: ${{ inputs.java-version }}
          spark-binary-version: ${{ inputs.spark-binary-version }}
          scala-binary-version: ${{ inputs.scala-binary-version }}
          repository: ${{ inputs.gluten-repository }}
          ref: ${{ inputs.gluten-ref }}

  upload-all-engine:
    name: Upload all engine jars
    runs-on: ubuntu-latest
    needs: [build-comet, build-auron, build-gluten]
    steps:
      - name: Get date
        id: get-date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Get cached Datafusion Comet lib
        uses: actions/cache/restore@v5
        with:
          path: comet-spark-spark${{ inputs.spark-binary-version }}_${{ inputs.scala-binary-version }}-*.jar
          key: ${{ needs.build-comet.outputs.cache-key }}
          fail-on-cache-miss: 'true'
      - name: Get cached Auron lib
        uses: actions/cache/restore@v5
        with:
          path: auron-spark-${{inputs.spark-binary-version}}*.jar
          key: ${{ needs.build-auron.outputs.cache-key }}
          fail-on-cache-miss: 'true'
      - name: Get cached gluten lib
        uses: actions/cache/restore@v5
        with:
          path: gluten-velox-bundle-spark*.jar
          key: ${{ needs.build-gluten.outputs.cache-key }}
          fail-on-cache-miss: 'true'
      - name: Upload native engine jars
        uses: actions/upload-artifact@v6
        with:
          name: spark_native_jars_${{ inputs.spark-binary-version }}_${{ inputs.scala-binary-version }}-${{ steps.get-date.outputs.date }}
          path: |
            comet-spark-spark${{ inputs.spark-binary-version }}_${{ inputs.scala-binary-version }}-*.jar
            gluten-velox-bundle-spark*.jar
            auron-spark-${{inputs.spark-binary-version}}*.jar
