name: Run comet change benchmark

on:
  workflow_call:
    inputs:
      os:
        default: 'ubuntu-latest'
        required: false
        type: string
      java-version:
        default: '8'
        required: false
        type: string
      spark-version:
        default: '3.5.4'
        required: false
        type: string
      spark-binary-version:
        default: '3.5'
        required: false
        type: string
      scala-version:
        default: '2.12.17'
        required: false
        type: string
      scala-binary-version:
        default: '2.12'
        required: false
        type: string
      benchmark:
        description: 'Benchmark to run (tpcds or tpch)'
        required: true
        type: string
      benchmark-scale:
        description: 'Scale factor for benchmark, like: tiny, 1, 10, 100, 1000...'
        required: true
        type: string
      comet-repository-first:
        default: 'apache/datafusion-comet'
        description: 'The repository of first comet to build'
        required: false
        type: string
      comet-ref-first:
        default: 'main'
        description: 'The commit id of first comet to build'
        required: false
        type: string
      comet-repository-second:
        default: 'apache/datafusion-comet'
        description: 'The repository of second comet to build'
        required: false
        type: string
      comet-ref-second:
        description: 'The commit id of second comet to build'
        required: true
        type: string

permissions:
  issues: write

jobs:
  build-comet-first:
    name: Build Datafusion Comet (First)
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v5
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}
      - name: Build Datafusion Comet (First)
        uses: ./.github/actions/build-comet
        with:
          java-version: ${{ inputs.java-version }}
          spark-binary-version: ${{ inputs.spark-binary-version }}
          scala-binary-version: ${{ inputs.scala-binary-version }}
          repository: ${{ inputs.comet-repository-first }}
          ref: ${{ inputs.comet-ref-first }}
      - name: Upload comet jar (First)
        uses: actions/upload-artifact@v6
        with:
          name: comet_jar_first_${{ inputs.benchmark }}-${{ inputs.benchmark-scale }}
          path: comet-spark-spark${{ inputs.spark-binary-version }}_${{ inputs.scala-binary-version }}-*.jar

  build-comet-second:
    name: Build Datafusion Comet (Second)
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v5
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}
      - name: Build Datafusion Comet (Second)
        uses: ./.github/actions/build-comet
        with:
          java-version: ${{ inputs.java-version }}
          spark-binary-version: ${{ inputs.spark-binary-version }}
          scala-binary-version: ${{ inputs.scala-binary-version }}
          repository: ${{ inputs.comet-repository-second }}
          ref: ${{ inputs.comet-ref-second }}
      - name: Upload comet jar (Second)
        uses: actions/upload-artifact@v6
        with:
          name: comet_jar_second_${{ inputs.benchmark }}-${{ inputs.benchmark-scale }}
          path: comet-spark-spark${{ inputs.spark-binary-version }}_${{ inputs.scala-binary-version }}-*.jar

  run-benchmark:
    name: Run benchmark
    runs-on: ${{ inputs.os }}
    needs: [build-comet-first, build-comet-second]
    steps:
      - uses: actions/checkout@v5
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}
      - name: Get cached benchmark lib
        uses: actions/cache/restore@v5
        with:
          path: benchmarks-spark-native-*.jar
          key: benchmarks-spark-native-lib-${{ hashFiles('pom.xml', '**/*.scala', '**/*.java') }}
          fail-on-cache-miss: 'true'
      - name: Get cached benchmark data
        uses: actions/cache/restore@v5
        with:
          path: |
            data/warehouse/*
            data/metastore/*
            check_files_${{ inputs.benchmark }}/*
          key: benchmarks-data-${{ inputs.benchmark }}-${{ inputs.benchmark-scale }}
          fail-on-cache-miss: 'true'
      - name: Setup Spark
        uses: ./.github/actions/setup-spark
        with:
          spark-version: ${{ inputs.spark-version }}
          scala-binary-version: ${{ inputs.scala-binary-version }}
      - name: Download comet jar (First)
        uses: actions/download-artifact@v7
        with:
          name: comet_jar_first_${{ inputs.benchmark }}-${{ inputs.benchmark-scale }}
          path: engine-jars/first
      - name: Download comet jar (Second)
        uses: actions/download-artifact@v7
        with:
          name: comet_jar_second_${{ inputs.benchmark }}-${{ inputs.benchmark-scale }}
          path: engine-jars/second
      - name: Run benchmark on spark with comet (First)
        run: |
          rm -f $SPARK_HOME/jars/comet-spark-spark*.jar
          cp $(pwd)/engine-jars/first/comet-spark-spark${{ inputs.spark-binary-version }}_${{ inputs.scala-binary-version }}-*.jar $SPARK_HOME/jars/
          WAREHOUSE_PATH=$(pwd)/data/warehouse
          METASTORE_PATH=$(pwd)/data/metastore
          BENCHMARK_JAR=$(ls benchmarks-spark-native-*.jar)
          $SPARK_HOME/bin/spark-submit \
            --master local\[4\] \
            --conf spark.sql.warehouse.dir=$WAREHOUSE_PATH \
            --conf spark.hadoop.javax.jdo.option.ConnectionURL=jdbc:derby:\;databaseName=$METASTORE_PATH\;create=true \
            --conf spark.driver.memory=4g \
            --conf spark.plugins=org.apache.spark.CometPlugin \
            --conf spark.comet.enabled=true \
            --conf spark.shuffle.manager=org.apache.spark.sql.comet.execution.shuffle.CometShuffleManager \
            --conf spark.memory.offHeap.enabled=true \
            --conf spark.memory.offHeap.size=4g \
            --conf spark.comet.columnar.shuffle.unifiedMemoryAllocatorTest=true \
            --class cn.wangz.spark.benchmarks.Main \
            $BENCHMARK_JAR \
            benchmark --type=${{ inputs.benchmark }} --scale=${{ inputs.benchmark-scale }} --output=benchmark-results/comet-first
      - name: Run benchmark on spark with comet (Second)
        run: |
          rm -f $SPARK_HOME/jars/comet-spark-spark*.jar
          cp $(pwd)/engine-jars/second/comet-spark-spark${{ inputs.spark-binary-version }}_${{ inputs.scala-binary-version }}-*.jar $SPARK_HOME/jars/
          WAREHOUSE_PATH=$(pwd)/data/warehouse
          METASTORE_PATH=$(pwd)/data/metastore
          BENCHMARK_JAR=$(ls benchmarks-spark-native-*.jar)
          $SPARK_HOME/bin/spark-submit \
            --master local\[4\] \
            --conf spark.sql.warehouse.dir=$WAREHOUSE_PATH \
            --conf spark.hadoop.javax.jdo.option.ConnectionURL=jdbc:derby:\;databaseName=$METASTORE_PATH\;create=true \
            --conf spark.driver.memory=4g \
            --conf spark.plugins=org.apache.spark.CometPlugin \
            --conf spark.comet.enabled=true \
            --conf spark.shuffle.manager=org.apache.spark.sql.comet.execution.shuffle.CometShuffleManager \
            --conf spark.memory.offHeap.enabled=true \
            --conf spark.memory.offHeap.size=4g \
            --conf spark.comet.columnar.shuffle.unifiedMemoryAllocatorTest=true \
            --class cn.wangz.spark.benchmarks.Main \
            $BENCHMARK_JAR \
            benchmark --type=${{ inputs.benchmark }} --scale=${{ inputs.benchmark-scale }} --output=benchmark-results/comet-second
      - name: Run benchmark on vanilla spark
        run: |
          rm -f $SPARK_HOME/jars/comet-spark-spark*.jar
          WAREHOUSE_PATH=$(pwd)/data/warehouse
          METASTORE_PATH=$(pwd)/data/metastore
          BENCHMARK_JAR=$(ls benchmarks-spark-native-*.jar)
          $SPARK_HOME/bin/spark-submit \
            --master local\[4\] \
            --conf spark.sql.warehouse.dir=$WAREHOUSE_PATH \
            --conf spark.hadoop.javax.jdo.option.ConnectionURL=jdbc:derby:\;databaseName=$METASTORE_PATH\;create=true \
            --conf spark.driver.memory=8g \
            --class cn.wangz.spark.benchmarks.Main \
            $BENCHMARK_JAR \
            benchmark --type=${{ inputs.benchmark }} --scale=${{ inputs.benchmark-scale }} --output=benchmark-results/vanilla
      - name: Generate comparison
        run: |
          pip install -r requirements.txt
          python scripts/generate-comparison.py \
            benchmark-results/vanilla/${{ inputs.benchmark }}_${{ inputs.benchmark-scale }}.json benchmark-results/comet-first/${{ inputs.benchmark }}_${{ inputs.benchmark-scale }}.json benchmark-results/comet-second/${{ inputs.benchmark }}_${{ inputs.benchmark-scale }}.json \
            --labels "Spark" "Comet First" "Comet Second" \
            --benchmark "${{ inputs.benchmark }}" --title "${{ inputs.benchmark }}-${{ inputs.benchmark-scale }}"
      - name: Upload comparison
        uses: actions/upload-artifact@v6
        with:
          name: comparison_${{ inputs.benchmark }}-${{ inputs.benchmark-scale }}
          path: |
            *_allqueries.png
            *_queries_compare.png
            *_queries_speedup_*.png
